name: Compile goat for Linux

on:
  workflow_dispatch:
  push:
    paths:
      - 'goat.cpp'

jobs:
    build-linux:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Install dependencies
            run: sudo apt-get install -y g++

          - name: Compile Goat
            run: g++ -O3 -march=native -flto -s -o goat goat-fast.cpp -pthread

          - name: Upload artifact
            uses: actions/upload-artifact@v4
            with:
              name: goat-linux
              path: goat
    build-windows:
      runs-on: windows-latest

      steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Developer command prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compile goat.cpp
        run: cl /O2 /GL /EHcs /GS- /Oi /Oy /GT /Gy /Gw /fp:fast /std:c++20 /MT goat.cpp /link /LTCG /OPT:REF /OPT:ICF

      - name: Upload goat-fast.exe
        uses: actions/upload-artifact@v4
        with:
          name: goat-windows
          path: goat.exe
