name: Compile Goat

on:
  push:
    paths:
      - 'goat-fast.cpp'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Developer command prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Compile goat.cpp
      run: cl /O2 /GL /EHcs /GS- /Oi /Oy /GT /Gy /Gw /fp:fast /std:c++20 /arch:AVX512 /MT goat-fast.cpp /link /LTCG /OPT:REF /OPT:ICF

    - name: Upload goat-fast.exe
      uses: actions/upload-artifact@v4
      with:
        name: goat-fast
        path: goat-fast.exe
